---
title: "create_static_map"
author: "tksym"
date: today
params:
  in1: "../data/polygon"
  in2: null
  dir_out: null
format:
  html:
    toc: true
    toc-depth: 3
    toc-location: right
    fig-format: png
    embed-resources: true
    self-contained-math: true
    code-fold: true
    code-overflow: wrap
  pdf:
    toc: false
editor: 
  mode: source
---

```{r}
#| label: setup
#| include: false

knitr::opts_chunk$set(
  fig.width = 16,
  fig.height = 9,
  dpi = 120,
  out.width = "100%",
  fig.align = "center",
  cache = FALSE
)

time_start <- Sys.time()
```

```{r}
#| label: packages
#| 
pacman::p_load(
  # data import
  here,
  fs,
  readxl,
  
  # data manipulation
  tidyverse,
  
  # gis,
  sf,
  
  # map
  terra,
  tidyterra,
  
  # misc
  tictoc,
  sessioninfo,
  report
)


```

```{r}
#| label: othersettings
#| include: false

# assign from outside
in1 <- params$in1
in2 <- params$in2
dir_out <- params$dir_out

```

# WORK FLOW

- Import data

- Edit data

- Visualize

- Export

# DATA

Table data: `{r} fs::path_rel(in1)`

Polygon directory: `{r} fs::path_rel(in2)`

Output directory: `{r} fs::path_rel(dir_out)`



# Import

```{r}

# ============================================== #
# import polygon

# list all shapefiles
shp_files <- list.files(
  in1,
  pattern = "\\.shp$",
  full.names = TRUE, 
  recursive = FALSE
)


# view file names
basename(shp_files)

# read all shapefiles
shp_list <- shp_files |>
  setNames(tools::file_path_sans_ext(basename(shp_files))) |>
  map(read_sf)



# ============================================== #
# import cleaned studyarea data
studyarea <- readr::read_csv(
  here("result", "create_leaflet_map", "studyarea_color_expanded.csv")
)


# ============================================== #
# import natural earth terrain tifs

# ---- #
# download these data here, store them locally
# 
# relief1: Cross Blended Hypso with Relief, Water, Drains, and Ocean Bottom, large size
# https://www.naturalearthdata.com/downloads/10m-raster-data/10m-cross-blend-hypso/
#
#
# relief2: Natural Earth I with Shaded Relief, Water, and Drainages, large size
# https://www.naturalearthdata.com/downloads/10m-raster-data/10m-natural-earth-1/
# 
# relief3: Natural Earth II with Shaded Relief, Water, and Drainages
# https://www.naturalearthdata.com/downloads/10m-raster-data/10m-natural-earth-2/
# ---- #


# !! Change path to local filename !! 

relief1 <- terra::rast(
  "C:/Users/81801/Desktop/er_review_grp/naturalearth/HYP_HR_SR_OB_DR/HYP_HR_SR_OB_DR.tif"
)

relief2 <- terra::rast(
  "C:/Users/81801/Desktop/er_review_grp/naturalearth/NE1_HR_LC_SR_W_DR/NE1_HR_LC_SR_W_DR.tif"
)

relief3 <- terra::rast(
  "C:/Users/81801/Desktop/er_review_grp/naturalearth/NE2_HR_LC_SR_W_DR/NE2_HR_LC_SR_W_DR.tif"
)


# relief1 <- terra::rast(
#   "C:/Users/wisdo/Dropbox/02_proj_cloud/GIS_data/naturalearth/HYP_HR_SR_OB_DR/HYP_HR_SR_OB_DR.tif"
# )
# 
# relief2 <- terra::rast(
#   "C:/Users/wisdo/Dropbox/02_proj_cloud/GIS_data/naturalearth/NE1_HR_LC_SR_W_DR/NE1_HR_LC_SR_W_DR.tif"
# )
# 
# relief3 <- terra::rast(
#   "C:/Users/wisdo/Dropbox/02_proj_cloud/GIS_data/naturalearth/NE2_HR_LC_SR_W_DR/NE2_HR_LC_SR_W_DR.tif"
# )




# ============================================== #
# import cleaned reviewdata table

rt_cleaned <- readr::read_csv(
  here("result", "reviewtable_organize", "rt_cleaned.csv")
)

```




# Edit data

```{r}

# names(shp_list)
# names(shp_list)[1]
# plot(shp_list[[1]])


# ============================================== #
# create numeric id for publication id

# ============================================== #
# create numeric id for publication id

rt_distinct <- rt_cleaned %>% 
  distinct(publication_id) %>% 
  mutate(
    publication_no = row_number()
  )


# ============================================== #
# match table data with polygon data

studyarea2 <- studyarea %>%
  left_join(
    rt_distinct,
    by = "publication_id"
  ) %>%
  mutate(
    shp = shp_list[shp_name]
  )


studyarea_cleaned <- studyarea2 %>%
  group_by(shp_name) %>%
  summarise(
    realm = first(realm),
    publication_no = paste(
      sort(unique(publication_no)),
      collapse = ", "
    ),
    color = first(color),
    shp = list(shp[[1]]),
    .groups = "drop"
  )


# ============================================== #
# combine polygons for plotting

studyarea_sf <- studyarea_cleaned %>%
  select(
    shp_name,
    realm,
    publication_no,
    color,
    shp
  ) %>%
  pmap_dfr(
    function(
      shp_name,
      realm,
      publication_no,
      color,
      shp
    ) {
      
      shp %>%
        mutate(
          shp_name = shp_name,
          realm = realm,
          publication_no = publication_no,
          color = color
        )
    }
  )

sf::st_bbox(studyarea_sf)

xlim_japan <- c(118,150)
ylim_japan <- c(22,48)





# ============================================== #
# crop to Japan

japan_ext <- terra::ext(
  c(xlim_japan, ylim_japan)
)

relief1_japan <- terra::crop(relief1, japan_ext)
relief2_japan <- terra::crop(relief2, japan_ext)
relief3_japan <- terra::crop(relief3, japan_ext)

terra::plotRGB(
  relief1_japan,
  r = 1,
  g = 2,
  b = 3,
  stretch = "lin"
)

terra::plotRGB(
  relief2_japan,
  r = 1,
  g = 2,
  b = 3,
  stretch = "lin"
)

terra::plotRGB(
  relief3_japan,
  r = 1,
  g = 2,
  b = 3,
  stretch = "lin"
)




```




# Visualize 1: use natural earth country map

```{r}

# ============================================== #
# prepare background map

world <- rnaturalearth::ne_countries(
  scale = 50,
  returnclass = "sf"
)



# ============================================== #
# plot

g <- ggplot() +
  
  geom_sf(
    data = world,
    fill = "grey95",
    color = "grey70",
    linewidth = 0.2
  ) +
  
  geom_sf(
    data = studyarea_sf,
    aes(
      fill = color,
      color = color
    ),
    linewidth = 0.4,
    alpha = 0.6
  ) +
  
  scale_fill_identity() +
  scale_color_identity() +
  
  coord_sf(
    xlim = xlim_japan,
    ylim = ylim_japan,
    expand = FALSE
  ) +
  
  theme_void()

g
```



# Visualize 2: use natural earth releif map

```{r}
#| fig-width: 12
#| fig-height: 12



# ============================================== #
# plot

g <- ggplot() +
  
  geom_spatraster_rgb(
    data = relief1_japan,
    maxcell = 1e6
  ) +
  
  geom_sf(
    data = studyarea_sf,
    aes(
      fill = color,
      color = color
    ),
    linewidth = 0.5,
    alpha = 0.6
  ) +
  
  scale_fill_identity() +
  scale_color_identity() +
  
  coord_sf(
    xlim = xlim_japan,
    ylim = ylim_japan,
    expand = FALSE
  ) +
  
  theme_void()

g


# ============================================== #
# plot

g <- ggplot() +
  
  geom_spatraster_rgb(
    data = relief1_japan,
    maxcell = 1e6
  ) +
  
  geom_sf(
    data = studyarea_sf,
    aes(
      fill = color,
      color = color
    ),
    linewidth = 1,
    alpha = 0.2
  ) +
  
  scale_fill_identity() +
  scale_color_identity() +
  
  coord_sf(
    xlim = xlim_japan,
    ylim = ylim_japan,
    expand = FALSE
  ) +
  
  theme_void()

g






# ============================================== #
# prepare polygon labels

studyarea_label <- studyarea_sf %>%
  group_by(
    shp_name,
    publication_no
  ) %>%
  summarise(
    geometry = sf::st_union(geometry),
    .groups = "drop"
  ) %>%
  sf::st_point_on_surface() %>%
  mutate(
    point_x = sf::st_coordinates(.)[, 1],
    point_y = sf::st_coordinates(.)[, 2],
    
    # initially put label at polygon location
    label_x = point_x,
    label_y = point_y
  ) %>%
  sf::st_drop_geometry()



# ============================================== #
# plot

g <- ggplot() +
  
  geom_spatraster_rgb(
    data = relief1_japan,
    maxcell = 1e6
  ) +
  
  geom_sf(
    data = studyarea_sf,
    aes(
      fill = color,
      color = color
    ),
    linewidth = 1,
    alpha = 0.2
  ) +
  
  ggrepel::geom_text_repel(
    data = studyarea_label,
    aes(
      x = label_x,
      y = label_y,
      label = publication_no
    ),
    size = 3,
    color = "black",
    min.segment.length = 0,
    segment.color = "black",
    segment.linewidth = 0.5,
    arrow = arrow(
      length = unit(0.3, "cm"),
      type = "closed",
      ends = "first"
    ),
    seed = 1
  ) +
  
  scale_fill_identity() +
  scale_color_identity() +
  
  coord_sf(
    xlim = xlim_japan,
    ylim = ylim_japan,
    expand = FALSE
  ) +
  
  theme_void()

g


# update lat, lon manually
studyarea_label %>%
  select(
    shp_name,
    publication_no,
    point_x,
    point_y,
    label_x,
    label_y
  )

# ---- #
# # A tibble: 19 × 6
#    shp_name                                  publication_no point_x point_y label_x label_y
#    <chr>                                     <chr>            <dbl>   <dbl>   <dbl>   <dbl>
#  1 e0009_koreastrait_cropped                 2                 125.    33.8    125.    33.8
#  2 e0029_daisetsu                            16                143.    43.5    143.    43.5
#  3 e0267_hakkoda                             12                141.    40.7    141.    40.7
#  4 e0400_recreate                            13                136.    34.6    136.    34.6
#  5 e0406_miyagi                              3                 141.    38.4    141.    38.4
#  6 e0434_hokkaido_recreate_cropped           11                143.    43.4    143.    43.4
#  7 e1585_centralwesternsector_cropped        14                136.    38.0    136.    38.0
#  8 e1667_eastchina_recreate_cropped          17                128.    33.1    128.    33.1
#  9 e1667_pacificcoast_recreate_cropped       17                134.    32.5    134.    32.5
# 10 e1991_centralwesternsector_0mbuff_cropped 5                 133.    36.8    133.    36.8
# 11 e2241_pacificcoast_cropped                1                 161.    43.6    161.    43.6
# 12 e_jgm1_easterncoast_cropped               8                 141.    35.8    141.    35.8
# 13 e_jgm1_westerncoast_cropped               8                 138.    37.3    138.    37.3
# 14 e_saki1_mtfuji_recreate                   10                139.    35.4    139.    35.4
# 15 j0198_rishiri                             7                 141.    45.2    141.    45.2
# 16 j_ogawa16_iwate                           18                141.    39.6    141.    39.6
# 17 j_ogawa1_recreate                         6                 134.    34.9    134.    34.9
# 18 japan_marine_recreate_cropped             8, 9, 15          131.    35.4    131.    35.4
# 19 japan_recreate                            4                 143.    43.5    143.    43.5
# ---- #


# label_manual <- tibble::tribble(
#   ~shp_name, ~publication_no, ~point_x, ~point_y, ~label_x, ~label_y,
#   "e0009_koreastrait_cropped",                 "9",        125.1, 33.8, 125.1, 33.8, 
#   "e0029_daisetsu",                            "2",        143.1, 44, 140.0, 44,
#   "e0267_hakkoda",                             "5",        140.9, 40.7, 143.0, 40.7,
#   "e0400_recreate",                          "6",        136.0, 34.6, 138.0, 33.0,
#   "e0406_miyagi",                              "10",       140.8, 38.4, 143.0, 38.4,
#   "e0434_hokkaido_recreate_cropped",           "3",        144.0, 43.5, 144.0, 45.0,
#   "e1585_centralwesternsector_cropped",        "12",       136.1, 38.0, 136.0, 38.0,
#   "e1667_eastchina_recreate_cropped",          "13",       127.9, 33.1, 128.0, 33.1,
#   "e1667_pacificcoast_recreate_cropped",       "13",       133.9, 32.5, 138.0, 32.5,
#   "e1991_centralwesternsector_0mbuff_cropped", "14",       132.7, 36.8, 133.0, 36.8,
#   "e2241_pacificcoast_cropped",                "15",       161.5, 43.6, 161.0, 43.6,
#   "e_jgm1_easterncoast_cropped",               "7",        141.0, 35.8, 141.0, 35.8,
#   "e_jgm1_westerncoast_cropped",               "7",        137.9, 37.3, 138.0, 37.3,
#   "e_saki1_mtfuji_recreate",                   "1",        138.7, 35.4, 139.0, 35.4,
#   "j0198_rishiri",                             "18",       141.2, 45.2, 140.0, 45.2,
#   "j_ogawa16_iwate",                           "4",        141.4, 39.6, 143.0, 39.6,
#   "j_ogawa1_recreate",                 "16",       134.1, 33, 134.0, 30.0,
#   "japan_recreate",                                     "17, 19",   140, 36, 143.0, 36.0,
#   "japan_marine_recreate_cropped",             "7, 8, 11", 143, 34, 146.0, 34
# )

label_manual <- tibble::tribble(
  ~shp_name, ~publication_no, ~point_x, ~point_y, ~label_x, ~label_y,
  "e0009_koreastrait_cropped",                 "2",         125.1, 33.8, 125.1, 35.5, 
  "e0029_daisetsu",                            "16",        143.1, 44,   143.9, 45.2,
  "e0267_hakkoda",                             "12",        140.9, 40.7, 137.6, 42.0,
  "e0400_recreate",                            "13",        136.0, 34.6, 138.0, 32.3,
  "e0406_miyagi",                              "3",         140.8, 38.4, 145.3, 38.4,
  "e0434_hokkaido_recreate_cropped",           "11",        144.0, 43.5, 146.2, 45.2,
  "e1585_centralwesternsector_cropped",        "14",        136.1, 38.0, 136.1, 40.8,
  "e1667_eastchina_recreate_cropped",          "17",        127.9, 33.1, 125.1, 32.5,
  "e1667_pacificcoast_recreate_cropped",       "17",        133.9, 32.5, 133.9, 30.8,
  "e1991_centralwesternsector_0mbuff_cropped", "5",         132.7, 36.8, 130.5, 36.8,
  "e2241_pacificcoast_cropped",                "1",         161.5, 43.6, 161.0, 43.6,
  "e_jgm1_easterncoast_cropped",               "8",         141.0, 35.8, 145.0, 34.5,
  "e_jgm1_westerncoast_cropped",               "8",         137.9, 37.3, 138.2, 39.6,
  "e_saki1_mtfuji_recreate",                   "10",        138.7, 35.4, 145.0, 33.0,
  "j0198_rishiri",                             "7",         141.2, 45.2, 139.4, 45.2,
  "j_ogawa16_iwate",                           "18",        141.4, 39.6, 145.3, 39.9,
  "j_ogawa1_recreate",                         "6",         134.1, 33,   136.5, 30.8,
  "japan_recreate",                            "4",         140,   36,   145.0, 36.0,
  "japan_marine_recreate_cropped",             "8, 9, 15",  143,   33,   144.5, 30.8
)


studyarea_label2 <- studyarea_label %>%
  select(
    shp_name, publication_no) %>%
  left_join(
    label_manual,
    by = c("shp_name", "publication_no")
  ) %>%
  mutate(
    dx = point_x - label_x,
    dy = point_y - label_y,
    dist = sqrt(dx^2 + dy^2),

    seg_x = label_x + 0.8 * dx / dist, #ラベルの根元をずらす
    seg_y = label_y + 0.8 * dy / dist
  )



g <- ggplot() +
  
  geom_spatraster_rgb(
    data = relief1_japan,
    maxcell = 1e6
  ) +
  
  geom_sf(
    data = studyarea_sf,
    aes(
      fill = color,
      color = color
    ),
    linewidth = 1,
    alpha = 0.2
  ) +
  
  geom_segment(
    data = studyarea_label2,
    aes(
      x = seg_x, #根本
      y = seg_y,
      xend = point_x, #先端
      yend = point_y
    ),
    inherit.aes = FALSE,
    linewidth = 0.4, #矢印の線の太さ
    color = "black",
    arrow = arrow(
      length = unit(0.15, "cm"), #矢じりの大きさ
      type = "closed"
    )
  ) +
  
  geom_text(
    data = studyarea_label2,
    aes(
      x = label_x,
      y = label_y,
      label = publication_no
    ),
    inherit.aes = FALSE,
    size = 8,
    color = "black"
  ) +
  
  scale_fill_identity() +
  scale_color_identity() +
  
  coord_sf(
    xlim = xlim_japan,
    ylim = ylim_japan,
    expand = FALSE
  ) +
  
  theme_void()

g


```

# Export

```{r}
# ============================================== #
# save figure

ggsave(
  filename = file.path(dir_out, "studyarea_map.pdf"),
  plot = g,
  width = 15,
  height = 15,
  units = "cm"
)

ggsave(
  filename = file.path(dir_out, "studyarea_map.png"),
  plot = g,
  width = 15,
  height = 15,
  units = "cm",
  dpi = 300
)



```








# Session info

```{r}
#| label: session-info

sessioninfo::session_info()
```

```{r}
#| label: run-info
#| echo: false

time_end <- Sys.time()
elapsed_sec <- as.numeric(difftime(time_end, time_start, units = "secs"))
elapsed_min <- as.numeric(difftime(time_end, time_start, units = "mins"))

readr::write_lines(
  c(
    paste("rendered_at:", Sys.time()),
    paste("input_file:", in1),
    paste("input_file:", in2),
    paste("output_dir:", dir_out),
    paste("run_time_seconds:", round(elapsed_sec, 1)),
    paste("run_time_minutes:", round(elapsed_min, 2))),
  file.path(dir_out, "run_info.txt")
)
```
